 name: Newman CLI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Set Timezone to Kolkata
    - name: Set Timezone
      run: |
        sudo timedatectl set-timezone "Asia/Kolkata"  # Set to Kolkata time zone
        date  # Print the date to confirm the change

    # Create a directory to store artifacts like reports
    - name: Create dir
      run: |
        mkdir SampleArtifact

    # Install Node.js
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '17.x'

    # Install Newman and Reporter
    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    # Run the Postman Collection
    - name: Run Collection
      run: |
        newman run "Assignment API Test.postman_collection.json" -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html

    # Publish the Report
    - name: Publish Report
      uses: actions/upload-artifact@v3
      with:
        name: Reports
        path: SampleArtifact
